name: Deploy S3 with Terraform

on:
  push:
    branches:
      - '*'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform for Network
        working-directory: ./network
        run: terraform init -backend-config="bucket=bucket-tfstates-postech-fiap-6soat" -backend-config="key=infra.tfstate" -backend-config="region=us-east-1"

      - name: Plan Terraform changes for Network
        working-directory: ./network
        run: terraform plan -out=tfplan

      - name: Apply Terraform changes for Network
        working-directory: ./network
        run: terraform apply -input=false tfplan

      - name: Initialize Terraform for Cognito
        working-directory: ./cognito
        run: terraform init -backend-config="bucket=bucket-tfstates-postech-fiap-6soat" -backend-config="key=cognito.tfstate" -backend-config="region=us-east-1"

      - name: Plan Terraform changes for Cognito
        working-directory: ./cognito
        run: terraform plan -out=tfplan

      - name: Apply Terraform changes for Cognito
        working-directory: ./cognito
        run: terraform apply -input=false tfplan