name: Destroy infra with Terraform

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform for Network
        working-directory: ./network
        run: terraform init -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="key=infra.tfstate" -backend-config="region=us-east-1"

      - name: Apply Terraform changes for Network
        working-directory: ./network
        run: terraform destroy -auto-approve